# 开发环境配置文件
server:
  port: 8080

spring:
#  profiles:
#    active: dev
  application:
    name: RISE-function
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=GMT%2B8
    driver-class-name:  com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    # 修改springboot默认数据源为Druid
    type: com.alibaba.druid.pool.DruidDataSource
    # 数据源(Druid连接池)其他配置
    ## 初始化连接数量
    initialSize: 5
    ## 最小空闲连接数
    minIdle: 5
    ## 最大并发连接数
    maxActive: 20
    ## 配置获取连接等待超时的时间
    maxWait: 60000
    ##  配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    ## 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    # filters: stat,wall,logback
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  # 清除缓存
  thymeleaf:
    cache: false

