management:
  metrics:
    web:
      server:
        auto-time-requests: false

server:
  port: 9000

zipkin:
  storage:
    # 通过 elasticsearch 来存储数据
    type: elasticsearch
    elasticsearch:
      cluster: elasticsearch
      hosts: http://localhost:9200
      index: zipkin