server:
  port: 6000

# Eureka配置
eureka:
  client:
    serviceUrl:
      # eureka服务端提供的注册地址 参考服务端配置的这个路径
      defaultZone: http://localhost:3000/eureka/
  instance:
    # 此实例注册到eureka服务端的唯一的 实例ID （集群中通过实例ID区分微服务）
    instance-id: power-0
    # 是否显示IP地址
    prefer-ip-address: true
    # Eureka客户需要多长时间发送心跳给eureka服务器,表明它仍然活着, 默认为30秒 (与下面配置的单位都是秒)
    leaseRenewalIntervalInSeconds: 1
    # Eureka服务器在接收到实例的最后一次发出的心跳后,需要等待多久才可以将此实例删除, 默认为90秒
    leaseExpirationDurationInSeconds: 3

# spring配置
spring:
  application:
    # 此实例注册到 Eureka服务端的名字
    # 在集群中使用时，相同的服务部署到两个机器上是，此处的Eureka服务端名字一样
    name: server-power
  zipkin:
    # 指定 zipkin-server 的地址
    base-url: http://localhost:9000
  sleuth:
    sampler:
      # request采样的数量标准默认是0.1, 也就是10%, 顾名思义：采取10%的请求数据(请求链),因为在分布式系统
      probability: 1.0