<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>com.study</groupId>
    <artifactId>study-project-java</artifactId>
    <packaging>pom</packaging>
    <version>1.0-SNAPSHOT</version>
    <name>parent-project</name>

    <modules>
        <module>java</module>
        <module>design-pattern</module>
        <!--框架学习 -->
        <module>spring-study</module>
        <module>springboot-study</module>
        <module>mybatis-study</module>
        <module>web-study</module>
        <!-- 工具整理 -->
        <module>utils</module>
        <module>springcloud-study</module>
        <module>redis-study</module>
        <module>netty-study</module>
        <module>dubbo-study</module>
        <module>zookeeper-study</module>
        <module>algorithm-study</module>
        <module>sharding-sphere-study</module>
        <module>data-migration-study</module>
        <module>ELK-study</module>
        <module>lucene-study</module>
    </modules>

    <properties>
        <maven.compiler.source>1.8</maven.compiler.source>
        <maven.compiler.target>1.8</maven.compiler.target>
        <spring.version>5.0.9.RELEASE</spring.version>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
        </dependency>
    </dependencies>

    <!-- 添加此插件导致无法进行整个项目的 mvn clean -->
    <!--<build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <target>1.8</target>&lt;!&ndash; 源代码使用的JDK版本 &ndash;&gt;
                    <source>1.8</source>&lt;!&ndash; 需要生成的目标class文件的编译版本 &ndash;&gt;
                    <encoding>UTF-8</encoding>&lt;!&ndash; 字符集编码 &ndash;&gt;
                </configuration>
            </plugin>
        </plugins>
    </build>-->

</project>