<project>
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.study.springcloud</groupId>
        <artifactId>springcloud-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <artifactId>ms-gateway-service</artifactId>
    <packaging>jar</packaging>
    <description>spring cloud学习：网关服务</description>

    <dependencies>
        <!-- spring cloud的网关依赖 -->
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <!-- nacos服务发现依赖 -->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
    </dependencies>

    <build>
        <!-- 服务打包的最终名称 -->
        <finalName>ms-gateway-service-app</finalName>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>
