server:
  port: 5000

# Eureka配置
eureka:
  client:
    serviceUrl:
      # eureka服务端提供的注册地址 参考服务端配置的这个路径
      defaultZone: http://localhost:3000/eureka/
#      defaultZone: http://eureka3000.com:3000/eureka/,http://eureka3001.com:3001/eureka/,http://eureka3002.com:3002/eureka/
  instance:
    # 此实例注册到eureka服务端的唯一的 实例ID （集群中通过实例ID区分微服务）
    instance-id: user
    # 是否显示IP地址
    prefer-ip-address: true
    # Eureka客户需要多长时间发送心跳给eureka服务器,表明它仍然活着,默认为30秒 (与下面配置的单位都是秒)
    leaseRenewalIntervalInSeconds: 10
    # Eureka服务器在接收到实例的最后一次发出的心跳后,需要等待多久才可以将此实例删除,默认为90秒
    leaseExpirationDurationInSeconds: 30

# spring配置
spring:
  application:
    # 此实例注册到 Eureka服务端的名字
    # 在集群中使用时，相同的服务部署到两个机器上是，此处的Eureka服务端名字一样
    name: server-user
    #
  zipkin:
    # 指定 zipkin-server 的地址
    base-url: http://localhost:9000
  sleuth:
    sampler:
      # request采样的数量标准默认是0.1, 也就是10%, 顾名思义：采取10%的请求数据(请求链),因为在分布式系统
      probability: 1.0

hystrix:
  # 命令属性
  command:
    # default 配置的全局的,所有的
    default:
      execution:
        isolation:
          thread:
            # 调用微服务超时监听,单位毫秒,默认设置为1秒
            timeoutInMilliseconds: 5000
      # 自定义为10秒内出现5次调用请求出现错误,熔断打开,从源头禁止调用微服务
      circuitBreaker:
        # 设置熔断的时间片段（滚动窗口）,单位毫秒, 默认是5秒
        sleepWindowInMilliseconds: 10000
        # 设置熔断打开的请求失败次数，设为5次
        requestVolumeThreshold: 5

  # 线程属性
  threadpool:
    # 域级别,default表示此微服务中线程池数量默认为 10
    default:
      coreSize: 10
    # 此处的power是在UserController配置的
    # @HystrixCommand(fallbackMethod = "getPowerFallBack",
    #                 threadPoolKey = "power", // 配置线程池的唯一ID
    #                 threadPoolProperties = {@HystrixProperty(name = "coreSize", value = "1") // 配置线程池属性
    # })
    power:
      coreSize: 5

# feign默认是支持hystrix的，但是D版本以后,feign中是默认关闭hystrix的
# feign打开hystrix
feign:
  hystrix:
    enabled: true

# spring Cloud对应的spring boot 2版本之前不需要下面这个配置
management:
  endpoints:
    web:
      exposure:
        include: '*'
