server:
  port: 3002
eureka:
  server:
    # 表示 关闭自我保护机制
    enable-self-preservation: false
    # 表示 设置清理时间间隔（单位：毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000
  instance:
    hostname: eureka3002.com
    instance-id: eureka3002

  client:
    # 表示不把自己作为一个客户端注册到自己身上
    registerWithEureka: false
    # 表示 不需要从服务端获取注册信息（因为在这里自己就是服务端，而且已经禁用了注册自己了）
    fetchRegistry: false
    serviceUrl:
      # 其他微服务客户端(EurekaClient) 注册到 微服务的服务端(EurekaServer)时，微服务客户端的地址就是下面这个defaultZone
      # 服务端配置集群
      defaultZone: http://eureka3000.com:3000/eureka,http://eureka3001.com:3001/eureka

spring:
  application:
    name: eureka3