spring.redis.host=192.168.80.4
spring.redis.port=6379
spring.redis.password=123456
# spring boot data 默认支持lettuce作为客户端，所以可以直接使用 lettuce配置连接池；不设置该连接池，则无法获取该客户端实例
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-idle=8
spring.redis.lettuce.pool.min-idle=0
spring.redis.lettuce.pool.max-wait=1000ms
# spring boot data 如果想要使用Jedis作为客户端，那么需要添加Jedis的相关依赖，然后配置连接池配置
# spring.redis.jedis.pool.max-active=