server:
  servlet:
    # 该配置只在web中有效，在webflux中无效
    context-path: /springBootDemo
# 使用dev的环境
spring:
  profiles:
    active: dev

# 特有的配置：配置两个环境, 通过 --- 分割
---
spring:
  profiles: prod
server:
  port: 8081
---
spring:
  profiles: dev
server:
  port: 8082


# 将自己配置的yml映射到java类中
user:
  id: 1
  name: allen
  birthDate: 2020/20/20
  # 映射集合方法一
  pets: [dog,cat]
  # 映射集合方法二
  cars:
    - redCar
    - blackCar
    - blueCar
  power:
    id: 1
    powerId: work-001