<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.study</groupId>
        <artifactId>study-project-java-2023</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <groupId>com.study.jvm</groupId>
    <artifactId>jvm-study</artifactId>
    <packaging>pom</packaging>
    <name>jvm底层学习</name>
    <modules>
        <module>jvm-basic-demo</module>
        <module>jvm-classloader-demo</module>
        <module>jvm-running-data-area-demo</module>
        <module>jvm-gc-demo</module>
        <module>jvm-actual-combat</module>
        <module>jmh-test</module>
    </modules>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>3.8.1</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

</project>
