# eureka服务单应用的端口默认配置
server.port=9000

# 表示是否将自己注册到Eureka服务端,默认为true,由于当前应用就是Eureka Server,所以设置为false
eureka.client.register-with-eureka=false
# 表示是否从Eureka服务端获取注册信息,默认为true,因为这是要给单点的Eureka Server,所以不需要同步其他
eureka.client.fetch-registry=false

#eureka.client.service-url.defaultZone=http://www.eureka9000.com:9000/eureka/
eureka.client.service-url.defaultZone=http://localhost:9000/eureka/