/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_study_JniExampleDemo */

#ifndef _Included_com_study_JniExampleDemo
#define _Included_com_study_JniExampleDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_study_JniExampleDemo
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_study_JniExampleDemo_set
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_study_JniExampleDemo
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_study_JniExampleDemo_get
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
