logging:
  pattern:
    dateformat: HH:mm:ss:SSS
  level:
    com.study.mq: debug
spring:
  rabbitmq:
    host: 192.168.80.4 # rabbitMQ的ip地址
    port: 5672 # 端口
    username: allen
    password: 123456
    virtual-host: /
    publisher-confirm-type: correlated  # 开启publisher-confirm，这里支持两种类型: simple 同步等待； correlated 异步回调，MQ返回结果时会回调这个ConfirmCallback
    publisher-returns: true # 开启publish-return功能，同样是基于callback机制，不过是定义ReturnCallback
    template:
      mandatory: true # 定义消息路由失败时的策略：true，则调用ReturnCallback；false：则直接丢弃消息