<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>com.study</groupId>
        <artifactId>study-project-java-2023</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>
    <groupId>com.study.juc</groupId>
    <artifactId>juc-study</artifactId>
    <packaging>pom</packaging>
    <name>java多线学习</name>
    <modules>
        <module>case_java7</module>
        <module>case_java8</module>
        <module>case_monitor</module>
        <module>case_thirdpart</module>
        <module>case_tomcat</module>
        <module>jcstress_ordering</module>
        <module>jmh_eliminate_locks</module>
        <module>jmh_performance</module>
    </modules>

</project>
