server:
  port: 9002

# Eureka配置
eureka:
  client:
    serviceUrl:
      # eureka服务端提供的注册地址 参考服务端配置的这个路径
      defaultZone: http://localhost:3000/eureka/
  #      defaultZone: http://eureka3000.com:3000/eureka/,http://eureka3001.com:3001/eureka/,http://eureka3002.com:3002/eureka/
  instance:
    # 此实例注册到eureka服务端的唯一的 实例ID （集群中通过实例ID区分微服务）
    instance-id: zuul-2
    # 是否显示IP地址
    prefer-ip-address: true
    # Eureka客户需要多长时间发送心跳给eureka服务器,表明它仍然活着,默认为30秒 (与下面配置的单位都是秒)
    leaseRenewalIntervalInSeconds: 1
    # Eureka服务器在接收到实例的最后一次发出的心跳后,需要等待多久才可以将此实例删除,默认为90秒
    leaseExpirationDurationInSeconds: 3

# spring配置
spring:
  application:
    # 此实例注册到 Eureka服务端的名字
    # 在集群中使用时，相同的服务部署到两个机器上是，此处的Eureka服务端名字一样
    name: server-zuul

# zuul配置
zuul:
  # ignored-services: "*"   禁用所有微服务默认路径
  # 禁用server-power微服务默认路径 忽略掉原来默认的路由路径，即 http://localhost:9000/server-power/getPower.do 等
  ignored-services: server-power

  prefix: /api

  # 路由配置调用其余微服务的路径,
  # 如果不配置,那么路径默认是 ip:port/微服务名称/具体请求路径，实例：http://localhost:9000/server-power/getPower.do
  routes:
    # 配置 server-power 微服务路径
    power:
      # 路由具体的微服务的服务名称
      serviceId: server-power
      # /power/*  表示：power/getPower.do       一层
      # /power/** 表示：power/admin/getPower.do 多层
      path: /power/**
    # 配置 server-order 微服务路径
    order:
      serviceId: server-order
      path: /order/**

  # 路由后的地址是否去除掉配置的前缀"/api", 默认是 true
  strip-prefix: true

