log4j.rootLogger=INFO,console

# 输出到控制台
log4j.appender.console=org.apache.log4j.ConsoleAppender
log4j.appender.console.target=System.out
# log4j.appender.console.target=System.err 打印出来日志是红色的
log4j.appender.console.layout=org.apache.log4j.PatternLayout
log4j.appender.console.layout.ConversionPattern=[%d{yyyy-MM-dd HH:mm:ss}] [%p] [%t] [%C.%M(%L)] | %m%n
# 2021-01-14 21:15:49,939 INFO [main] org.springframework.context.support.AbstractApplicationContext.prepareRefresh(513) | Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@f2a0b8e: startup date [Thu Jan 14 21:15:49 CST 2021]; root of context hierarchy