server:
  port: 8081
spring:
  application:
    name: ms-cache-item-service
  datasource:
    url: jdbc:mysql://192.168.80.4:3306/cache_demo
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 192.168.80.4
    port: 6379
mybatis-plus:
  type-aliases-package: com.study.cache.pojo
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto
logging:
  level:
    com.study.cache: debug
  pattern:
    dateformat: HH:mm:ss:SSS
canal:
  destination: cache_demo    # canal的集群名字，要与安装canal时设置的名称一致
  server: 192.168.80.4:11111 # canal服务地址